<a href="https://colab.research.google.com/github/Omar03-maker/Learning_Pyhton_Ml/blob/main/notebook_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jour 8 - 22 Juillet 2026 : NumPy Avancé

Aujourd'hui, nous allons voir comment manipuler la structure des tableaux et filtrer des données intelligemment.

## 1. Reshape (Changer la forme)
Très utile en Machine Learning pour réorganiser des données. Par exemple, transformer un tableau de 12 éléments en une matrice 3x4.

In [4]:
import numpy as np
a = np.arange(12) # Crée un tableau de 0 à 11
print("Tableau 1D initial :", a)

b = a.reshape(3, 4) # 3 lignes, 4 colonnes
print("\nMatrice 3x4 :\n", b)

Tableau 1D initial : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Matrice 3x4 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 2. Masques booléens (Filtrage)
Le masque booléen consiste à filtrer un tableau en utilisant une condition. Cela renvoie un tableau de `True` et `False`, qu'on peut appliquer au tableau pour ne garder que les `True`.

In [5]:
ages = np.array([15, 22, 18, 30, 16, 25])

# Qui est majeur ?
majeur = ages >= 18
print("Masque booléen :", majeur)

# Appliquons le masque
print("Ages majeurs :", ages[majeur])

Masque booléen : [False  True  True  True False  True]
Ages majeurs : [22 18 30 25]


---
## 🏆 Défi du Jour 8

1. Créez un tableau `notes` contenant : [8, 12, 15, 9, 17, 5, 11].
2. Utilisez un masque booléen pour créer un nouveau tableau `notes_valides` ne contenant que les notes supérieures ou égales à 10.
3. Affichez `notes_valides`.

In [6]:
# 1. Création du tableau notes
notes = np.array([8, 12, 15, 9, 17, 5, 11])

# 2. Masque booléen : True si la note est >= 10
masque_valides = notes >= 10

# On applique le masque au tableau pour ne garder que les notes valides
notes_valides = notes[masque_valides]

# 3. Affichage
print("Notes valides :", notes_valides)

Notes valides : [12 15 17 11]
